run:
  timeout: 5m
  tests: false
  modules-download-mode: readonly

output:
  format: colored-line-number
  sort-results: true

linters:
  disable-all: true
  enable:
    - gofmt
    - govet
    - goconst
    - gosimple
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - misspell

linters-settings:
  gofmt:
    simplify: true
  misspell:
    locale: US
  govet:
    check-shadowing: true

issues:
  exclude-use-default: false
  exclude:
    - "should have a package comment"
    - "comment should be of the form"
  exclude-rules:
    - path: "_test.go"
      linters:
        - unparam
    - path: "migrations"
      linters:
        - deadcode
